### ISSUE TITLE
Add options for products

### ISSUE THREAD

**Issue by jtaaa** [SYSTT/sellyourstuff#100]
These options can have their own price, description?, stock and pictures.
This may include changes to the product link where we display a range of prices instead of just one.

**Comment by jarryon** [comment]
I can show you a killer implementation of varients/options on products from software I've worked with for inventory management - www.vendhq.com - honestly one of my favourite. I have backend access to some accounts

**Comment by jtaaa** [comment]
Thank would be very useful
