### ISSUE TITLE
Add verification process for digital payments

### ISSUE THREAD

**Issue by jtaaa** [SYSTT/sellyourstuff#11]
Initial sign up is easy. Verification is slightly harder because we need documents.

Allow for uploading all the necessary documents. Check against the database to ensure no multiple accounts for one business.

**Comment by jarryon** [comment]
We are targeting registered small businesses as our first customers.

We will require them to submit the same verification information as WiPay requires depending on their type of business.

https://wipaycaribbean.com/kyc-table
