### ISSUE TITLE
Seller receives packing and delivery instructions

### ISSUE THREAD

**Issue by jtaaa** [SYSTT/sellyourstuff#16]

**Comment by jarryon** [comment]
What packing & delivery instructions are necessary?

Well..what's happening?

Seller got a sale!

Seller receives instruction from SYS to get the product ready for delivery.

What does seller need?

They need the buyer to be happy with the purchase!

They need to ensure they properly protect the package for shipping.

They need a box appropriately sized for the package they're selling.

If the product is fragile, they need to ensure they have some sort of packing foam or other protective material.

They need to know what date & time the driver will be picking up the package.

They need to receive a notification when their package has been collected.

They need to receive a notification when their package has been delivered.
