### ISSUE TITLE
Integration with WiPay

### ISSUE THREAD

**Issue by jtaaa** [SYSTT/sellyourstuff#18]

**Comment by jarryon** [comment]
Credit Card API is available but not a WiPay Signup API. Our SELLERS will have to also signup for a WiPay account via WiPay's website to accept credit card payments on our website.

WiPay has intentions to release a Sign Up API in 2020. I will pressure them to build it for us.

**Comment by jarryon** [comment]
https://wipaycaribbean.com/credit-card-documentation/
