### ISSUE TITLE
Instructions to withdraw payment to their bank account

### ISSUE THREAD

**Issue by jtaaa** [SYSTT/sellyourstuff#25]

**Comment by jarryon** [comment]
Ideally, a seller can withdraw payment to their bank account by visiting their user profile & selecting 'Get Paid' or 'Withdraw to Bank Account' which will pull the seller's funds from their WiPay account & push them to their bank account. This depends on how integrated SYS can become with WiPay.

Alternatively, a seller:

1. logs onto their WiPay account: https://www.wipayfinancial.com/v1/
2. Selects 'Accounts' from the top menu
3. Selects 'Bank Withdrawal' from the dropdown
4. Enters the amount & selects 'Withdraw'.

WiPay takes a $5 fee to withdraw.
